export const SET_EXPENSES = "SET_EXPENSES";
export const SET_EXPENSE = "SET_EXPENSE";
export const ADD_EXPENSE = "ADD_EXPENSE";
export const UPDATE_EXPENSE = "UPDATE_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";


export const DATA_FETCHING_ERROR = "DATA_FETCHING_ERROR";